# Generated by Django 6.0.3 on 2026-04-06 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='time',
            old_name='fundacao',
            new_name='ano_fundacao',
        ),
    ]
